INSERT INTO DISTRICT (NAME, VALUE_PER_SQUARE_METER) VALUES ('Osasco', 10000.0);

-- INSERT INTO ROOM (AREA, LENGTH, WIDTH, NAME) VALUES (0.0, 10.0, 12.0, 'sala', 1);
-- INSERT INTO ROOM (AREA, LENGTH, WIDTH, NAME) VALUES (0.0, 10.0, 18.0, 'quarto', 1);

INSERT INTO PROPERTY (NAME, DISTRICT_ID) VALUES ('casa1', 1);


